[versions]
kotlin = "2.0.21"
junit = "4.13.2"
gradle = "8.2.2"
vanniktech = "0.28.0"
koin = "3.5.6"
kover = "0.8.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin_test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin_gradle_plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech"}
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
